name: Python-Calculator-CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
      - name: Print coverage tool version
        run: |
          coverage --version
      - name: Print current directory
        run: |
          pwd

      - name: Run tests and generate coverage report
        run: |
          coverage run -m unittest src/test_calculator.py
          coverage report -m > coverage.txt
