name: Python-Calculator-CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      - name: Print coverage tool version
        run: |
          coverage --version

      - name: Run tests and generate coverage report
        run: |
          cd $GITHUB_WORKSPACE  # Move to the root directory of the repository
          coverage run -m unittest src/test_calculator.py
          coverage report -m --omit=*/venv/* --fail-under=100
          mv coverage.txt $GITHUB_WORKSPACE/coverage.txt  # Move coverage.txt to the root directory
