name: Python-Calculator-CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: mahesh-VirtualBox   # Specify the runner at the job level

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          coverage --version
          
      - name: Run tests and generate coverage report
        run: |
          cd src
          coverage run -m unittest test_calculator.py
          coverage report -m > coverage.txt
  code-coverage:
    needs: test
    runs-on: mahesh-VirtualBox   # Specify the runner at the job level

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: src/coverage.txt

  upload-artifact:
    needs: code-coverage
    runs-on: mahesh-VirtualBox   # Specify the runner at the job level

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: calculator-artifact
          path: src  # Adjust the path to include the directory containing your artifact
